document.write("<footer class=\"section-padding\">");
document.write("	<div class=\"container\">");
document.write("		<div class=\"row\">");
document.write("			<!-- About Footer -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"about-footer\">");
document.write("					<p>Mischa vd Goes<br>Visual Designer");
document.write("				<\/div>");
document.write("			<\/div><!-- Social -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"social\">");
document.write("					<ul>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/www.instagram.com\/mischades\/\"><i class=\"fab fa-instagram\"><\/i><\/a>");
document.write("						<\/li>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/www.behance.net\/mfgoes\"><i class=\"fab fa-behance\"><\/i><\/a>");
document.write("						<\/li>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/twitter.com\/cell3d_game\"><i class=\"fab fa-twitter\"><\/i><\/a>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("				<\/div>");
document.write("			<\/div><!-- Copy -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"copy about-footer\">");

document.write("					<p>Portfolio 2020<br>Amsterdam, NL<\/p>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/footer>");
