document.write("<footer class=\"section-padding\">");
document.write("	<div class=\"container\">");
document.write("		<div class=\"row\">");
document.write("			<!-- About Footer -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"about-footer\">");
document.write("					<img alt=\"logo\" src=\"img\/logo\/logocircle.svg\">");
document.write("					<p>CONTACT ME:<br>");
document.write("					mischvdgoes@gmail.com<\/p>");
document.write("				<\/div>");
document.write("			<\/div><!-- Social -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"social\">");
document.write("					<ul>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/www.instagram.com\/mvdgdes\/\"><i class=\"fab fa-instagram\"><\/i><\/a>");
document.write("						<\/li>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/www.behance.net\/mfgoes1b6a4\"><i class=\"fab fa-behance\"><\/i><\/a>");
document.write("						<\/li>");
document.write("						<li>");
document.write("							<a href=\"https:\/\/twitter.com\/mischavdg\"><i class=\"fab fa-twitter\"><\/i><\/a>");
document.write("						<\/li>");
document.write("					<\/ul>");
document.write("				<\/div>");
document.write("			<\/div><!-- Copy -->");
document.write("			<div class=\"col-lg-4 col-md-4 col-sm-12\">");
document.write("				<div class=\"copy\">");
document.write("					<p>Mischa van der Goes 2020<br>");
document.write("					All rights reserved<\/p>");
document.write("				<\/div>");
document.write("			<\/div>");
document.write("		<\/div>");
document.write("	<\/div>");
document.write("<\/footer>");
