document.write("    <nav class=\"navbar navbar-default navbar-fixed-top\">");
document.write("        <div class=\"container\">");
document.write("            <div class=\"navbar-header\">");
document.write("                <div class=\"navbar-toggle collapsed menu-icon\" data-toggle=\"collapse\" data-target=\"#menu\" aria-expanded=\"false\" role=\"button\">");
document.write("                    <div class=\"bar half start\"><\/div>");
document.write("                    <div class=\"bar\"><\/div>");
document.write("                    <div class=\"bar half end\"><\/div>");
document.write("                <\/div>");
document.write("                <a href=\"index.html\"><img class=\"navbar-brand\" src=\"img\/logo\/logo.svg\" alt=\"logo\"><\/a>");
document.write("            <\/div>");
document.write("            <div class=\"collapse navbar-collapse\" id=\"menu\" data-hover=\"dropdown\" data-animations=\"fadeInUp\">");
document.write("                <ul class=\"nav navbar-nav navbar-right\">");
document.write("                    <!-- Start Contact -->");
document.write("                    <li><a class=\"click-close\" href=\"index.html\">Home<\/a><\/li>");
document.write("                    <li class=\"dropdown\">");
document.write("                        <a href=\"index.html\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Works<\/a>");
document.write("                        <ul class=\"dropdown-menu\">");
document.write("							<li><a class=\"click-close\" href=\"crowdmedia.html\">Crowd Media<\/a><\/li>");
document.write("                            <li><a class=\"click-close\" href=\"evbox.html\">EVBox Web Page [NEW]<\/a><\/li>");
document.write("                            <li><a class=\"click-close\" href=\"bootcamp.html\">Social Bootcamp Brand<\/a><\/li>");
document.write("                            <li><a class=\"click-close\" href=\"salescompanion.html\">Sales Companion App<\/a><\/li>");
document.write("                            <li><a class=\"click-close\" href=\"posters.html\">Poster Designs<\/a><\/li>");
document.write("                            <li><a class=\"click-close\" href=\"index.html\">-See All-<\/a><\/li>");
document.write("                            ");
document.write("                        <\/ul>");
document.write("                    <\/li>");
document.write("                    <li><a class=\"click-close\" href=\"about-resume.html\">About<\/a><\/li>");
document.write("                    <li><a class=\"click-close\" href=\"contact.html\">Contact<\/a><\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("        <\/div>");
document.write("    <\/nav>");
