//converted using http://www.andrewdavidson.com/convert-html-to-javascript/
//Aug 2020
document.write( '<nav class=\"navbar navbar-default navbar-fixed-top\">\n' );
document.write( '        <div class=\"container\">\n' );
document.write( '            <div class=\"navbar-header\">\n' );
document.write( '                <div class=\"navbar-toggle collapsed menu-icon\" data-toggle=\"collapse\" data-target=\"#menu\" aria-expanded=\"false\" role=\"button\">\n' );
document.write( '                    <div class=\"bar half start\"></div>\n' );
document.write( '                    <div class=\"bar\"></div>\n' );
document.write( '                    <div class=\"bar half end\"></div>\n' );
document.write( '                </div>\n' );
document.write( '                <a href=\"index.html\"><img class=\"navbar-brand\" src=\"img/logo/logo.svg\" alt=\"logo\"></a>\n' );
document.write( '            </div>\n' );
document.write( '            <div class=\"collapse navbar-collapse\" id=\"menu\" data-hover=\"dropdown\" data-animations=\"fadeInUp\">\n' );
document.write( '                <ul class=\"nav navbar-nav navbar-right\">\n' );
document.write( '                    <!-- Start Contact -->\n' );
document.write( '                    <!--<li class=\"active dropdown\"><a class=\"click-close\" href=\"index.html\">My Work</a></li>-->\n' );
document.write( '                    <!-- End Contact -->\n' );
document.write( '                    <!-- Start Works -->\n' );
document.write( '                      <li class=\"dropdown\"><a href=\"index.html\" class=\"click-close dropdown-toggle\">My Work\n' );
document.write( '                        <ul class=\"dropdown-menu\">\n' );
document.write( '                            <li><a class=\"click-close\" href=\"tasteradar.html\">Tasteradar</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"mendix_old.html\">Mendix</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"crowdmedia.html\">Crowd Media</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"bootcamp.html\">Social Bootcamp</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"salescompanion.html\">Sales Companion App</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"posters.html\">Poster Designs</a></li>\n' );
document.write( '                            <li><a class=\"click-close\" href=\"index.html\">-See All-</a></li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </a>\n' );
document.write( '                    </li>\n' );
document.write( '                    <!-- End Works -->\n' );
document.write( '            \n' );
document.write( '                    <!-- Start About -->\n' );
document.write( '                    <li><a class=\"click-close\" href=\"about.html\">About</a></li>\n' );
document.write( '                    <!-- End About -->\n' );
document.write( '                    <!-- Start Contact -->\n' );
document.write( '                    <li><a class=\"click-close\" href=\"about.html#contact-section\">Contact</a></li>\n' );
document.write( '                    <!-- End Contact -->\n' );
document.write( '                </ul>\n' );
document.write( '            </div>\n' );
document.write( '        </div>\n' );
document.write( '    </nav>' );
